server:
  port: 80   # 80端口为HTTP上网冲浪使用次数最多的协议，浏览网页服务默认的端口号都是80，因此只需要输入网址即可

spring:
  application:
    name: cloud_consumer_order

eureka:
  client:
    #表示是否将自己注册金EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须配置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #  报错：Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8761/eureka/}
      #      问题描述：连接不到地址为 http://localhost:8761/eureka 的注册中心
      #      原因：服务中指定的 http://localhost:8890/eureka 注册中心地址无效，而用了springcloud默认的注册中心地址（defaultZone写错了）
      #      修改服务中的配置文件属性 default-zone为defaultZone
      #defaultZone: http://localhost:7001/eureka            # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

